//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonyMLR.DataAccess
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class race_info
    {
        public race_info()
        {
            this.race_result = new ObservableCollection<race_result>();
        }
    
        public int race_id { get; set; }
        public System.DateTime race_date { get; set; }
        public System.TimeSpan race_time { get; set; }
        public int track_key { get; set; }
        public string race_name { get; set; }
        public string race_restrictions_age { get; set; }
        public int race_class { get; set; }
        public decimal race_distance { get; set; }
        public Nullable<int> race_prize_money { get; set; }
        public string race_going { get; set; }
        public int race_number_of_runners { get; set; }
        public decimal race_finishing_time { get; set; }
    
        public virtual ObservableCollection<race_result> race_result { get; set; }
        public virtual racetrack racetrack { get; set; }
    }
}
